#!/biin/bash -e

#Author:  Jonathan Ingram
#Date:  1/29/18
#Assignment 1

cp matrix matrix_backup

clear

#TMP = "${@:2}$"
trap "rm -f $TMP; echo 'CTRL + C received , exiting'; exit 1" INT HUP TERM
#TMP = $1 {@:2}$ 

function dims(){

	if [[ $# -gt 1]];
	then
		echo "Error: Received more then 1 argument" >&2 #Writing to standard error
		exit -1
	fi
	if [[($# -eq 1 && !-f $1)]];
	then
		echo "$1 Error: No File Exists" >&2  #Writing to standard error
		exit -1
	fi

	#Print as required.
	echo "Row\tCols"
	exit 0
} 

function transpose(){
#This is from lecture 1.4
        if [[ $# -gt 1]];
        then
                echo "Error: Received more then 1 argument" >&2 #Writing to standard error
                exit -1
        fi
        if [[($# -eq 1 && !-f $1)]];
        then
                echo "$1 Error: No File Exists" >&2  #Writing to standard error
                exit -1
        fi

	exit 0

}

function mean(){
#lecture 1.5
        if [[ $# -gt 1]];
        then
                echo "Error: Received more then 1 argument" >&2 #Writing to standard error
                exit -1
        fi
        if [[($# -eq 1 && !-f $1)]];
        then
                echo "$1 Error: No File Exists" >&2  #Writing to standard error
                exit -1
        fi

	i = 0
	sum = 0
	count = 0
	mean = 0
	l_num = `expr $l_num + 1`
	echo "Processig line $l_num: $$myLine"

	for i in $myLine
	do
		number = $i
		count = `expr $count + 1`
		sum = `expr $sum + $number`
	done

	mean = `expr $sum/$count`
	echo "The mean of the matrix is: $mean"

	exit 0
}

function add(){
#Not sure is I need to add 2 matrices together or just numbers in a matrix
#I am assume that I need to add 2 matrices together
        if [[ $# -gt 2]];
        then
                echo "Error: Received more then 2 argument" >&2 #Writing to standard error
                exit -1
        fi
        if [[($# -eq 2 && !-f $1)]];
        then
                echo "$1 Error: No File Exists" >&2  #Writing to standard error
                exit -1
        fi

	i = 0

	read myLine
	sum_1 = "m1"
	sum_2 = "m2"
	sum = 0
	for i in $myLine
			 

	
	exit 0

}


function multiply(){
#I am assuming that I need to add 2 matrices together here
#I am assuming that I need to call my transpose function on the 2nd matrix to do that math

	if [[ $# -gt 2]];
        then
                echo "Error: Received more then 2 argument" >&2 #Writing to standard error
                exit -1
        fi
        if [[($# -eq 2 && !-f $1)]];
        then
                echo "$1 Error: No File Exists" >&2  #Writing to standard error
                exit -1
        fi

	exit 0
}

